# Generated by Django 4.2.11 on 2024-04-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot_app', '0002_faq'),
    ]

    operations = [
    ]
