# Generated by Django 4.2.11 on 2024-04-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot_app', '0005_chatmonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmonitor',
            name='fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmonitor',
            name='response_time',
            field=models.IntegerField(),
        ),
    ]
